name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ 安装 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 25.2.9519653 # 可选，如果用原生库
          cmake: 3.22.1     # 可选，如果用 CMake

      # 4️⃣ 设置 Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # 5️⃣ 构建 APK
      - name: Build Debug APK
        run: gradle :app:assembleDebug --stacktrace --info --no-daemon

      # 6️⃣ 上传 APK 到 Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: WzryAssistant-APK
          path: app/build/outputs/apk/debug/app-debug.apk
